apiVersion: v1
kind: ReplicationController
metadata:
  name: haproxy-ingress
  labels:
    app: haproxy-ingress
spec:
  replicas: 1
  selector:
    app: haproxy-ingress
  template:
    metadata:
      labels:
        app: haproxy-ingress
    spec:
      containers:
      - image: gcr.io/google_containers/haproxy-ingress:0.1
        imagePullPolicy: Always
        name: haproxy
        ports:
        - containerPort: 80
          hostPort: 80
